version: 0.2

env:
  #secrets-manager:
  RDS_HOST: "dev/aurora-pg/pg1/postgres:host"

phases:
  pre_build:
    commands:
      - echo $RDS_HOST:latest
      - aws --version
  build:
    commands:
      - echo build started on $(date)
  post_build:
    commands:
      - echo build completed on $(date)
artifacts:
  #files: imagedefinitions.json
